#!/usr/bin/env bash
# Local Android build — produces an installable APK for a REAL device
# without the Expo cloud (no EAS, no account), consistent with the
# project's Docker-only / no-external-services stance.
#
# iOS is intentionally NOT supported here: it needs macOS + Xcode + an
# Apple Developer account, none of which exist in this environment.
#
# This is a managed / Continuous-Native-Generation app: the native
# android/ project is GENERATED by `expo prebuild` and is gitignored.
# Treat it as ephemeral build output — never hand-edit it; rerun this
# script to regenerate.
#
# CRITICAL — build-time config embed: Expo bakes every EXPO_PUBLIC_*
# var into the JS bundle AT BUILD TIME. A real device has no
# `adb reverse`, and `localhost` resolves to the phone itself, so the
# API base MUST be a LAN-reachable / deployed gateway. This script
# refuses a loopback base unless ALLOW_LOCALHOST=1.
#
# Usage:
#   EXPO_PUBLIC_API_BASE_URL=http://192.168.0.14:8080/api npm run build:android
#   VARIANT=release ...        # default debug (no keystore needed);
#                              # release needs a signing config/keystore
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# --- toolchain (same discovery convention as scripts/e2e.sh) ---
: "${JAVA_HOME:=$(find "$HOME/android-tools" -maxdepth 1 -type d -name 'jdk-17*' 2>/dev/null | head -1)}"
export JAVA_HOME
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
[ -x "$JAVA_HOME/bin/java" ] || { echo "FATAL: JDK 17 not found (set \$JAVA_HOME)"; exit 1; }
command -v sdkmanager >/dev/null || { echo "FATAL: sdkmanager not on PATH (install Android cmdline-tools)"; exit 1; }

VARIANT="${VARIANT:-debug}"
case "$VARIANT" in
  debug|release) ;;
  *) echo "FATAL: VARIANT must be 'debug' or 'release'"; exit 1 ;;
esac

# --- API base guard (it is embedded at build time, not runtime) ---
API="${EXPO_PUBLIC_API_BASE_URL:-}"
if [ -z "$API" ] && [ -f .env ]; then
  API="$(grep -E '^EXPO_PUBLIC_API_BASE_URL=' .env | head -1 | cut -d= -f2-)"
fi
[ -n "$API" ] || {
  echo "FATAL: EXPO_PUBLIC_API_BASE_URL is not set (and not in .env)."
  echo "       It is baked into the bundle at build time — pass a reachable gateway."
  exit 1
}
if printf '%s' "$API" | grep -qiE 'localhost|127\.0\.0\.1|10\.0\.2\.2'; then
  if [ "${ALLOW_LOCALHOST:-0}" != 1 ]; then
    echo "FATAL: API base '$API' is loopback/emulator-only — useless on a real device."
    echo "       Set EXPO_PUBLIC_API_BASE_URL to a LAN/deployed gateway,"
    echo "       or ALLOW_LOCALHOST=1 to override (e.g. emulator-only build)."
    exit 1
  fi
  echo "WARN: building with loopback API base '$API' (ALLOW_LOCALHOST=1)"
fi
export EXPO_PUBLIC_API_BASE_URL="$API"
echo "==> API base embedded in the bundle: $API"

# --- generate the native project (CNG); deps already installed ---
echo "==> expo prebuild (android, --clean, no dep reinstall)"
npx --no-install expo prebuild --platform android --clean --no-install

# --- provision exactly the SDK packages the generated project needs ---
sdk_prop() { # $1 = gradle key suffix, e.g. compileSdkVersion
  local v
  v="$(grep -E "^android.$1=" android/gradle.properties 2>/dev/null | head -1 | cut -d= -f2)"
  [ -z "$v" ] && v="$(grep -oP "$1[^']*'\K[0-9.]+" android/build.gradle 2>/dev/null | head -1)"
  echo "$v"
}
COMPILE_SDK="$(sdk_prop compileSdkVersion)"; COMPILE_SDK="${COMPILE_SDK:-36}"
BUILD_TOOLS="$(sdk_prop buildToolsVersion)"; BUILD_TOOLS="${BUILD_TOOLS:-36.0.0}"
echo "==> ensuring SDK: platform-tools, platforms;android-$COMPILE_SDK, build-tools;$BUILD_TOOLS"
yes 2>/dev/null | sdkmanager --licenses >/dev/null 2>&1 || true
sdkmanager "platform-tools" "platforms;android-$COMPILE_SDK" "build-tools;$BUILD_TOOLS" >/dev/null

# --- gradle build ---
TASK=":app:assemble$(tr '[:lower:]' '[:upper:]' <<< "${VARIANT:0:1}")${VARIANT:1}"
echo "==> gradle $TASK (first run downloads Gradle + deps; this is slow)"
( cd android && ./gradlew "$TASK" --no-daemon --console=plain )

APK="android/app/build/outputs/apk/$VARIANT/app-$VARIANT.apk"
[ -f "$APK" ] || { echo "FATAL: expected APK not found at $APK"; exit 1; }
SIZE="$(du -h "$APK" | cut -f1)"
echo
echo "==> BUILD OK ($VARIANT, $SIZE): $ROOT/$APK"
echo "    install on a connected device:  adb install -r '$ROOT/$APK'"
